[manager]
show_hidden = true

[opener]

edit = [
	{ run = 'nvim "$@"', block = true },
]
view = [
    { run = 'librewolf "$@"', block = false},
]

[open]
prepend_rules = [
    {name = "*.pdf", use = "view"}
]
